import { client } from "@/sanity/lib/client";
import { Car } from "../schemas/car";
import { SanityCar, serializeCar } from "../utils/serialize-car";

export async function getCars({ locale }: { locale: string }): Promise<Car[]> {
  const query = '*[_type == "car"]';
  const cars = await client.fetch<SanityCar[]>(
    query,
    {},
    { next: { revalidate: 0 } },
  );

  return cars.map((car) => serializeCar({ car, locale }));
}

export async function _getCars({ locale }: { locale: string }): Promise<Car[]> {
  return [
    {
      id: "1",
      images: ["/images/landing/car-one.png"],
      price: 7500,
      location: "Fontaines-sur-Saône 69270",
      type: "Hatchback",
      brand: "Peugeot",
      model: "208",
      finish: "Intens 1.6 dCi Energy DC6 2020",
      equipments: ["GPS", "Bluetooth", "Air Conditionné"],
      interiorColor: "Grey",
      exteriorColor: "Silver",
      manufacturingYear: 2020,
      mileage: 50000,
      fuelType: "Diesel",
      critAir: "Yes",
      transmission: "Automatic",
      enginePower: "88 kW",
      doors: 5,
      seats: 5,
      publishedAt: new Date().toISOString(),
      isSold: true,
    },
    {
      id: "2",
      images: ["/images/landing/car-two.png"],
      price: 36800,
      location: "Chassieu 69680",
      type: "SUV",
      brand: "Mercedes",
      model: "GLC",
      finish: "220d 4 Matic AMG Line 2022",
      equipments: ["GPS", "Bluetooth", "Camera de recul", "Toit ouvrant"],
      interiorColor: "Black",
      exteriorColor: "Black",
      manufacturingYear: 2022,
      mileage: 15000,
      fuelType: "Diesel",
      critAir: "Yes",
      transmission: "Automatic",
      enginePower: "143 kW",
      doors: 5,
      seats: 5,
      publishedAt: new Date().toISOString(),
      isSold: true,
    },
    {
      id: "3",
      images: ["/images/landing/car-three.png"],
      price: 4500,
      location: "Champagne Au Mont d'Or 69120",
      type: "Hatchback",
      brand: "Renault",
      model: "Clio 3",
      finish: "Phase 2 1.2 100ch",
      equipments: ["Radio", "Air Conditionné"],
      interiorColor: "Black",
      exteriorColor: "Blue",
      manufacturingYear: 2010,
      mileage: 120000,
      fuelType: "Petrol",
      critAir: "No",
      transmission: "Manual",
      enginePower: "74 kW",
      doors: 5,
      seats: 5,
      publishedAt: new Date().toISOString(),
      isSold: true,
    },
    {
      id: "4",
      images: ["/images/landing/car-four.png"],
      price: 7200,
      location: "Lyon 69006",
      type: "Hatchback",
      brand: "Fiat",
      model: "500",
      finish: "Fiat 500c - 2018",
      equipments: ["GPS", "Bluetooth", "Toit ouvrant"],
      interiorColor: "Red",
      exteriorColor: "Grey",
      manufacturingYear: 2018,
      mileage: 50000,
      fuelType: "Petrol",
      critAir: "Yes",
      transmission: "Automatic",
      enginePower: "51 kW",
      doors: 3,
      seats: 4,
      publishedAt: new Date().toISOString(),
      isSold: true,
    },
    {
      id: "5",
      images: ["/images/landing/car-five.png"],
      price: 14990,
      location: "Villeurbanne 69100",
      type: "SUV",
      brand: "Peugeot",
      model: "2008",
      finish: "130ch GT Line Toit Ouvrant Panoramique CarPlay 2022",
      equipments: [
        "GPS",
        "Bluetooth",
        "Toit panoramique",
        "CarPlay",
        "Camera de recul",
      ],
      interiorColor: "Black",
      exteriorColor: "Black",
      manufacturingYear: 2022,
      mileage: 20000,
      fuelType: "Petrol",
      critAir: "Yes",
      transmission: "Automatic",
      enginePower: "96 kW",
      doors: 5,
      seats: 5,
      publishedAt: new Date().toISOString(),
      isSold: true,
    },
    {
      id: "6",
      images: ["/images/landing/car-six.png"],
      price: 8400,
      location: "Chassieu 69680",
      type: "Hatchback",
      brand: "Peugeot",
      model: "208",
      finish: "Intens 1.6 dCi Energy DC6 2023",
      equipments: ["GPS", "Bluetooth", "Air Conditionné"],
      interiorColor: "Grey",
      exteriorColor: "White",
      manufacturingYear: 2023,
      mileage: 30000,
      fuelType: "Diesel",
      critAir: "Yes",
      transmission: "Automatic",
      enginePower: "88 kW",
      doors: 5,
      seats: 5,
      publishedAt: new Date().toISOString(),
      isSold: true,
    },
    {
      id: "7",
      images: ["/images/landing/car-seven.png"],
      price: 7500,
      location: "Fontaines-sur-Saône 69270",
      type: "SUV",
      brand: "Volkswagen",
      model: "Tiguan",
      finish: "2.0 TDI 2016",
      equipments: ["GPS", "Bluetooth", "Camera de recul"],
      interiorColor: "Black",
      exteriorColor: "White",
      manufacturingYear: 2016,
      mileage: 100000,
      fuelType: "Diesel",
      critAir: "Yes",
      transmission: "Automatic",
      enginePower: "110 kW",
      doors: 5,
      seats: 5,
      publishedAt: new Date().toISOString(),
      isSold: true,
    },
    {
      id: "8",
      images: ["/images/landing/car-eight.png"],
      price: 7500,
      location: "Sauvegarde 69009",
      type: "Hatchback",
      brand: "Volkswagen",
      model: "Golf",
      finish: "Intens 1.6 dCi Energy DC6",
      equipments: ["GPS", "Bluetooth", "Air Conditionné"],
      interiorColor: "Black",
      exteriorColor: "Silver",
      manufacturingYear: 2020,
      mileage: 60000,
      fuelType: "Diesel",
      critAir: "Yes",
      transmission: "Automatic",
      enginePower: "88 kW",
      doors: 5,
      seats: 5,
      publishedAt: new Date().toISOString(),
      isSold: true,
    },
  ];
}
